### ISSUE TITLE
Can we use llama2 besides mistral model?

### ISSUE THREAD

**Issue by warengonzaga** [bonham000/kuzco-inference-client#1]
I'm curious if possible, but based on what I observed while running the worker most of them uses mistral why is that?

**Comment by bonham000** [comment]
@warengonzaga I'm not sure, the answer to that question lies with the Kuzco team.

**Comment by warengonzaga** [comment]
I see, thanks @bonham000 for the response. I'll close this now.

But do you know how to use llma2 with Kuzco?

**Comment by bonham000** [comment]
@warengonzaga no I'm not sure how, my guess is Kuzco is only testing Mistral at the moment.

**Comment by warengonzaga** [comment]
I see, thanks for the help!
